### ISSUE TITLE
Feature Request: Ability to configure Static IP, Gateway and Subnet Mask

### ISSUE THREAD

**Issue by Stormer2k0** [pkerspe/ESP-StepperMotor-Server#13]
It would be rather useful to be able to configure a static IP the same way you configure the SSID name and password.
You still can just add a static IP by just by adding this in the main:

```
IPAddress local_IP(10, 38, 4, 110);
IPAddress gateway(10, 38, 4, 1);
IPAddress subnet(255, 255, 255, 0);

if (!WiFi.config(local_IP, gateway, subnet)) {
    Serial.println("STA Failed to configure");
}
```
And if not adding static IP to the library then maybe add an example for the people who don't know how to do this.

**Comment by pkerspe** [comment]
@Stormer2k0 are you sure the syntax is correct?
According to https://www.arduino.cc/en/Reference/WiFiConfig you example is actually the method signature
```WiFi.config(ip, dns, gateway);```

**Comment by Stormer2k0** [comment]
@pkerspe I used this syntax as in WiFiSTA.cpp that is the order the function is written: 
![2020-10-09 12_36_50-WiFiSTA cpp - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/72493889/95573797-4a84fb80-0a2c-11eb-9b2d-918174286742.png)

dns1 and dns2 arn't nessesary as those have been given a default value in the constructor:
![2020-10-09 12_47_29-WiFiSTA h - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/72493889/95574747-caf82c00-0a2d-11eb-9715-eb08fe496dd8.png)

**Comment by pkerspe** [comment]
added in version v0.4.2
Example 3 shows how to use it.
```
 IPAddress staticIp(192, 168, 178, 49);
 IPAddress gatewayIp(192, 168, 178, 1);
 IPAddress subnetMask(255, 255, 255, 0);
 stepperMotorServer->setStaticIpAddress(staticIp, gatewayIp, subnetMask);
```

Or you can add the new config nodes to the json config file in the server config section:
```
...
{
  "serverConfiguration": {
...
    "staticIP": "192.168.178.49",
    "gatewayIP": "192.168.178.1",
    "subnetMask": "255.255.255.0"
  },
...
```

**Comment by pkerspe** [comment]
please test and report if all works as requested
