### ISSUE TITLE
no page update

### ISSUE THREAD

**Issue by dpsiddons** [pkerspe/ESP-StepperMotor-Server#32]
I'm using the Arduino version (UI version: 0.3.1 / Server version: 0.4.7). It works well, except the control page does not update after or during a motion. Only a manual page refresh brings in the new information. I tried on FIrefox and Chrome; same behavior. I expected that the page would update to reflect the motor status. Is this the correct behavior?

**Comment by pkerspe** [comment]
Hi @dpsiddons (Peter),

thanks for opening the issue. 
Usually the control page should open an socket connection to the server running on the ESP32 and should update the position information of the stepper motors in the UI with an update frequency of several Hz.
this is implemented in the later UI Versions. Current Version is 0.4.1 so the version you are using is a bit outdated. Your server version is ok, 0.4.8 is current, but this feature is already implemented in 0.4.7 as well.
So you just need to update your UI and it should be working fine.
