### ISSUE TITLE
Possibility to control enable pin on the A4988 driver module. Otherwise the motor uses power when not rotating.

### ISSUE THREAD

**Issue by amigafan** [pkerspe/ESP-StepperMotor-Server#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pkerspe** [comment]
@amigafan can you please provide some details on your feature request?

**Comment by amigafan** [comment]
My idea is to use an A4988 driver module together with a DRV8825 expansion board module.
This expandion module requires Step signal, Direction signal and an enabled signal. When enable signal is low the driver is enabled. If the enable signal is low all the time, the step motor uses power even when it is not rotating. I like the ability to configure stepper motor, limit switch and rotary encoder. Br. amigafan

**Comment by pkerspe** [comment]
Not sure why to combine those two boards but doesn't matter.
So if I get you right, you do not want manual control over the IO connected to the enable pin but simply want it to get pulled low whenever a move is in progress and pulled high when the movement stopped?
Correct?

**Comment by amigafan** [comment]
Yes, that is correctly understood. For some reason, the motor draws power as soon as the enable pin is low.

**Comment by pkerspe** [comment]
Probably the driver powers the coils to keep the motor from spinning freely, in order to maintain its position. If you remove power, depending on your setup and use case, you might loose absolute precision.

**Comment by amigafan** [comment]
That sounds like a good explanation, without power the shaft is easy to turn around with your fingers. For my use, though, it's no problem.

**Comment by pkerspe** [comment]
so for everyone having this issue you can now use the motor break function to control a driver enable pin. Basically instead of using it to activate a brake you use it to control the state of the enable pin when the motor is not moving:
  `void setBrakePin(signed char brakePin, byte activeState = ESP_FlexyStepper::ACTIVE_HIGH);`
