### ISSUE TITLE
Malformed JSON returned by /api/switches/status and /api/switches/status?id=<id> API

### ISSUE THREAD

**Issue by adpmdrones** [pkerspe/ESP-StepperMotor-Server#34]
The /api/switches/status and /api/switches/status?id=<id> does not return a correct JSON

i.e.
{
    status: 0000000000000011
}

the correct JSON must be

{
    "status": "0000000000000011"
}

**Comment by pkerspe** [comment]
@adpmdrones thanks for reporting this issue, I just pushed a possible fix.
I am currently traveling and thus could not test it on a real ESP32, but it should be fine now (I hope).

Please test release v0.4.9 and let me know if it works for you now
https://github.com/pkerspe/ESP-StepperMotor-Server/releases/tag/v0.4.9
