### ISSUE TITLE
ZIP archive doesn't contain a valid library (Arduino IDE)

### ISSUE THREAD

**Issue by jarcher12** [pkerspe/ESP-StepperMotor-Server#4]
getting this when trying to install from downloaded zip

Specified folder/zip file does not contain a valid library

**Comment by pkerspe** [comment]
@jarcher12 can you please provide more details? Which IDE are you using? 
Have you tried using the library manager of your IDE?

**Comment by pkerspe** [comment]
In case you are using Arduino (1.8 or above) download the latest release (0.2.3, I just added a library.properties file) and in use the import function in Arduino (somewhere under the "Sketch" menu.
I just tried with Arduino 1.8.13 and it works just fine.

**Comment by pkerspe** [comment]
@jarcher12 can you confirm the issue as solved?

**Comment by jarcher12** [comment]
Ok can install library, will try it out.
thanks
