### ISSUE TITLE
Make it possible to register additional cli commands

### ISSUE THREAD

**Issue by houz** [pkerspe/ESP-StepperMotor-Server#42]
I need to add additional commands to the serial interface for some custom functions.

It would be great if you could expose `ESPStepperMotorServer_CLI::registerNewCommand` and make it possible to access `ESPStepperMotorServer::cliHandler`. Alternatively you could add a wrapper if you prefer to not expose the class directly.

That way I could avoid forking the code base just for my own project and never getting around to merging in your updates.

I suppose something similar fore REST and web server would be handy, but I didn't look into that part of the code yet and won't need it for the time being.

**Comment by pkerspe** [comment]
Hi @houz, of course we can make functions public, would you be able to prepare a Pull Request with the suggested changes? I will review and merge
